title: "Two-Stage ASL Detection Architecture"
description: "A new two staged approach to Classify Hand sign (American Sign Language)"
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
